<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ __('program_title') }} | {{ __('app_name') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=ADLaM+Display&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/css/dashboard.css', 'resources/js/app.js'])
</head>
<body class="dashboard-page program-page">
    @php
        $isArabic = app()->getLocale() === 'ar';
    @endphp
    <x-dashboard-shell :is-arabic="$isArabic" active-page="program">
            <main class="dashboard-content program-content">
                <div class="birds-page-heading"><div><span class="dashboard-eyebrow">{{ __('program_upcoming') }}</span><h1>{{ __('program_title') }}</h1><p>{{ __('program_subtitle') }}</p></div><button class="dashboard-primary-button" type="button" data-open-task><span>+</span>{{ __('program_add') }}</button></div>
                <div class="program-layout">
                    <section class="panel calendar-panel"><div class="calendar-heading"><button class="calendar-nav" type="button" data-calendar-prev aria-label="Previous month">&#8592;</button><h2 data-calendar-title></h2><button class="calendar-nav" type="button" data-calendar-next aria-label="Next month">&#8594;</button></div><div class="calendar-weekdays" data-calendar-weekdays></div><div class="calendar-grid" data-calendar-grid></div></section>
                    <section class="panel tasks-panel"><div class="panel-heading"><div><span class="panel-kicker">{{ __('program_today') }}</span><h2>{{ __('program_upcoming') }}</h2></div></div><div class="task-list" data-task-list></div></section>
                </div>
            </main>
    </x-dashboard-shell>
    <div class="task-modal" data-task-modal hidden><form class="task-form" data-task-form><div class="task-form-heading"><div><span class="panel-kicker">{{ __('program_add') }}</span><h2>{{ __('program_task_title') }}</h2></div><button type="button" class="task-close" data-close-task aria-label="{{ __('program_task_cancel') }}">&times;</button></div><label>{{ __('program_task_title') }}<input name="title" required placeholder="{{ __('program_task_placeholder') }}"></label><div class="task-form-row"><label>{{ __('program_task_date') }}<input name="date" type="date" required></label><label>{{ __('program_task_type') }}<select name="type"><option>{{ __('program_type_care') }}</option><option>{{ __('program_type_breeding') }}</option><option>{{ __('program_type_health') }}</option><option>{{ __('program_type_other') }}</option></select></label></div><label>{{ __('program_task_notes') }}<textarea name="notes" rows="3" placeholder="{{ __('program_notes_placeholder') }}"></textarea><button class="dashboard-primary-button" type="submit">{{ __('program_task_save') }}</button></form></div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const sidebar = document.getElementById('dashboard-sidebar'); const overlay = document.querySelector('.sidebar-overlay'); const languageToggle = document.getElementById('dashboard-language-toggle'); const modal = document.querySelector('[data-task-modal]'); const form = document.querySelector('[data-task-form]'); const list = document.querySelector('[data-task-list]'); const grid = document.querySelector('[data-calendar-grid]'); const title = document.querySelector('[data-calendar-title]'); const weekdays = document.querySelector('[data-calendar-weekdays]'); const storageKey = 'wakr-program-tasks'; const isArabic = document.documentElement.lang === 'ar'; let currentMonth = new Date();
            const dayNames = isArabic ? ['أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت'] : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
            const setSidebar = (open) => { sidebar.classList.toggle('is-open', open); overlay.classList.toggle('is-visible', open); }; document.querySelector('[data-sidebar-open]').addEventListener('click', () => setSidebar(true)); document.querySelectorAll('[data-sidebar-close]').forEach((button) => button.addEventListener('click', () => setSidebar(false))); languageToggle.addEventListener('change', () => { window.location.href = languageToggle.checked ? languageToggle.dataset.arUrl : languageToggle.dataset.enUrl; });
            const getTasks = () => JSON.parse(localStorage.getItem(storageKey) || '[]'); const saveTasks = (tasks) => localStorage.setItem(storageKey, JSON.stringify(tasks)); const formatDate = (date) => date.toISOString().slice(0, 10);
            const renderTasks = () => { const tasks = getTasks().sort((a, b) => a.date.localeCompare(b.date)); list.innerHTML = tasks.length ? tasks.map((task) => `<article class="task-item"><span class="task-dot"></span><div><strong>${task.title}</strong><small>${task.date} · ${task.type}${task.notes ? ` · ${task.notes}` : ''}</small></div><button type="button" class="task-remove" data-remove-task="${task.id}" aria-label="Remove">&times;</button></article>`).join('') : '<p class="task-empty">{{ __('program_empty') }}</p>'; document.querySelectorAll('[data-remove-task]').forEach((button) => button.addEventListener('click', () => { saveTasks(getTasks().filter((task) => task.id !== Number(button.dataset.removeTask))); renderTasks(); renderCalendar(); })); };
            const renderCalendar = () => { const year = currentMonth.getFullYear(); const month = currentMonth.getMonth(); title.textContent = currentMonth.toLocaleDateString(isArabic ? 'ar' : 'en-US', { month: 'long', year: 'numeric' }); weekdays.innerHTML = dayNames.map((day) => `<span>${day}</span>`).join(''); const firstDay = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); const tasks = getTasks(); grid.innerHTML = ''; for (let index = 0; index < firstDay; index += 1) grid.insertAdjacentHTML('beforeend', '<span class="calendar-day is-muted"></span>'); for (let day = 1; day <= daysInMonth; day += 1) { const date = formatDate(new Date(year, month, day)); const dayTasks = tasks.filter((task) => task.date === date); grid.insertAdjacentHTML('beforeend', `<button type="button" class="calendar-day ${dayTasks.length ? 'has-task' : ''}" data-date="${date}"><strong>${day}</strong>${dayTasks.length ? `<i>${dayTasks.length}</i>` : ''}</button>`); } document.querySelectorAll('[data-date]').forEach((button) => button.addEventListener('click', () => { form.date.value = button.dataset.date; modal.hidden = false; form.title.focus(); })); };
            document.querySelector('[data-open-task]').addEventListener('click', () => { form.reset(); form.date.value = formatDate(new Date()); modal.hidden = false; form.title.focus(); }); document.querySelector('[data-close-task]').addEventListener('click', () => { modal.hidden = true; }); modal.addEventListener('click', (event) => { if (event.target === modal) modal.hidden = true; }); form.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(form); const tasks = getTasks(); tasks.push({ id: Date.now(), title: data.get('title'), date: data.get('date'), type: data.get('type'), notes: data.get('notes') }); saveTasks(tasks); modal.hidden = true; renderTasks(); renderCalendar(); }); document.querySelector('[data-calendar-prev]').addEventListener('click', () => { currentMonth.setMonth(currentMonth.getMonth() - 1); renderCalendar(); }); document.querySelector('[data-calendar-next]').addEventListener('click', () => { currentMonth.setMonth(currentMonth.getMonth() + 1); renderCalendar(); }); renderTasks(); renderCalendar();
        });
    </script>
</body>
</html>
